package com.auction.shared.dto;

/** Enum for message types between client and server. */
public enum MessageType {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  REGISTER,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  PLACE_BID,
  SETUP_AUTO_BID,
  BID_SUCCESS,
  BID_ERROR,
  NEW_BID_BROADCAST,
  AUCTION_ENDED,
  GET_STATUS,
  CREATE_ITEM,
  CREATE_ITEM_SUCCESS,
  CREATE_ITEM_FAIL,
  GET_SELLER_ITEMS,
  GET_SELLER_ITEMS_RESPONSE
}